---
title: "FAQ"
---

Cours donné à l'[École Normale Supérieure](https://www.ens.psl.eu/) au premier semestre de l'année 2024-2025, par Théo Boulakia, dans le cadre de [l'Observatoire des Humanités Numériques](https://odhn.ens.psl.eu/).

# Quand ?

Le **mercredi**, de 15h à 18h : 18 septembre, 25 septembre, 9 octobre, 23 octobre, 6 novembre, 13 novembre, 4 décembre et 18 décembre 2024.

# Où ?

Dans la salle de conférences du Centre de Sciences de données (ENS-PSL, 45 rue d'Ulm, tout en haut de l'escalier B ou C).

# Comment s'inscrire ?

Envoyez simplement un mail à l'adresse suivante : theo.boulakia[at]gmail.com. Indiquez votre formation, précisez si vous avez déjà une expérience en programmation ou des connaissances en statistiques.

# Est-il possible de venir en auditeur libre ?

Tout à fait. La validation n'est pas requise.

# Comment valider le cours ?

- Trouver des données qui vous intéressent. Elles peuvent correspondre à un intérêt personnel, à une recherche en cours ou à un projet de recherche futur.
- Leur appliquer une ou plusieurs des méthodes vues en cours.
- Rendre un document de 4 pages présentant les données, la problématique, les étapes de l'analyse et l'interprétation des résultats.

# Faut-il savoir coder ?

Non. Vous pouvez assister au cours même si vous n'avez jamais programmé. 