---
title: "Python"
---

# Pip & Venv

- Créer un nouveau repo github
- Le cloner avec `git clone https://...`
- Créer les sous-dossiers suivants : `data`, `src`, `notebooks`
- Créer un [environnement virtuel](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#upgrading-packages) `.venv`, à la racine du dossier.
- Activer l'environnement virtuel, installer les packages nécessaires. 
- Créer un fichier `requirements.txt` avec `pip freeze > requirements.txt`
- Créer un fichier `.gitignore`, ignorer `data/` et `.venv/`.
- add, commit & push

# Conda (recommandé)

- Installer Miniconda (voir Quick command line insatall, c'est l'affaire de 4 ou 5 commandes).
- Créer un environnement virtuel avec `conda create`
:::{.callout-note}
Par défaut, les environnement virtuels conda sont **centralisés** dans le dossier ~/miniconda3. C'est bien ainsi.
:::
- Activer cet environnement avec `conda activate`
- Installer les packages nécessaires, souvent avec le *chanel* conda-forge : `conda install -c conda-forge XXX`
- Installer Jupyter notebook (qui s'appelle `notebook`) et ipykernel (pas installé par défaut avec Jupyter notebook ?)
- Ajouter l'environnement virtuel aux kernels.
:::{.callout-note}
Les kernels jupyter sont stockés dans ~/.locale/share/jupyter/kernels sous la forme d'un fichier json. Si on supprime un environnement virtuel et qu'on ne veut plus qu'il apparaisse dans la page de sélection des kernels (pour Jupyterlab) ou le menu déroulant (pour Jupyter notebook), c'est ce dossier qu'il faut supprimer. 
:::
- Lancer jupyter notebook et sélectionner le kernel correspondant.