---
title: "Ressources"
---

# General

Wickham Hadley, Çetinkaya-Rundel Mine et Grolemund Garrett, *R for data science: import, tidy, transform, visualize, and model data*, 2e édition., O’Reilly, 2023, 548 p. [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)

McKinney Wes, *Python for data analysis: data wrangling with pandas, NumPy, and Jupyter*, 3e édition., O’Reilly, 2022, 579 p. [https://wesmckinney.com/book/](https://wesmckinney.com/book/)

Storopoli, Huijzer and Alonso *Julia Data Science*, 2021, 260 p. [https://juliadatascience.io](https://juliadatascience.io)

Kamiński Bogumił, *Julia for data analysis*, Manning, 2023, 443 p.

# DataViz

Wilke Claus, *Fundamentals of data visualization: a primer on making informative and compelling figures*, O’Reilly, 2019, 387 p. [https://clauswilke.com/dataviz/](https://clauswilke.com/dataviz/)

Healy Kieran, *Data visualization: a practical introduction*, Princeton University Press, 2019, 272 p.

# Geographic Data Science

Lovelace Robin, Nowosad Jakub et Muenchow Jannes, *Geocomputation with R*, 2e édition., Chapman & Hall / CRC, 2025, 424 p. [https://r.geocompx.org/](https://r.geocompx.org/)

Dorman Michael, Graser Anita, Nowosad Jakub et Lovelace Robin, *Geocomputation with Python*, Chapman & Hall / CRC, 2025, 344 p. [https://py.geocompx.org/](https://py.geocompx.org/)

Hoffimann Mendes Júlio, *Geospatial Data Science with Julia*, 2023. [https://juliaearth.github.io/geospatial-data-science-with-julia/](https://juliaearth.github.io/geospatial-data-science-with-julia/)

Rey Sergio J., Arribas-Bel Daniel et Wolf Levi John, *Geographic data science with Python*, Chapman & Hall / CRC, 2023, 378 p. [https://geographicdata.science/book/](https://geographicdata.science/book/)

Pebesma Edzer J. et Bivand Roger, *Spatial data science: with applications in R*, Chapman & Hall / CRC, 2023, 314 p. [https://r-spatial.org/book/](https://r-spatial.org/book/)

# Unsupervised Learning

Waggoner Philip D., *Modern Dimension Reduction*, Cambridge University Press, 2021, 98 p. [https://arxiv.org/abs/2103.06885](https://arxiv.org/abs/2103.06885)

Waggoner Philip D., *Unsupervised Machine Learning for Clustering in Political and Social Research*, Cambridge University Press, 2021, 70 p.

Giordani Paolo, Ferraro Maria Brigida et Martella Francesca, *An Introduction to Clustering with R*, Springer, 2020, 340 p.

# Statistics

Johnson Alicia A., Ott Miles Q. et Dogucu Mine, *Bayes rules! an introduction to Bayesian modeling with R*, Chapman & Hall / CRC, 2022, 544 p. [https://www.bayesrulesbook.com/](https://www.bayesrulesbook.com/)

McElreath Richard, *Statistical rethinking: a Bayesian course with examples in R and Stan*, 2e édition, Chapman & Hall / CRC, 2020, 612 p.

> À ma connaissance, il n'existe pas de version en libre accès de _Statistical Rethinking_. Le site suivant liste différentes "traductions" des exercices, à partir de différentes librairies et langages de programmation : [https://xcelab.net/rm/](https://xcelab.net/rm/) Voir notamment : [https://github.com/StatisticalRethinkingJulia](https://github.com/StatisticalRethinkingJulia)

Gelman Andrew, Hill Jennifer et Vehtari Aki, *Regression and other stories*, Cambridge University Press, 2020, 546 p. [https://avehtari.github.io/ROS-Examples/](https://avehtari.github.io/ROS-Examples/)

> Comme pour *Statistical Rethinking*, il y a eu une traduction en Julia, par Rob J Goedman : [https://github.com/RegressionAndOtherStoriesJulia](https://github.com/RegressionAndOtherStoriesJulia)

Davidson-Pilon Cameron, *Bayesian methods for hackers: probabilistic programming and Bayesian inference*, Addison-Wesley, 2016, 256 p. [http://dataorigami.net/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/](http://dataorigami.net/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/)

Kaplan Daniel T., *Statistical modeling: a fresh approach*, 2017, 388 p. [https://dtkaplan.github.io/SM2-bookdown/](https://dtkaplan.github.io/SM2-bookdown/)

 > Cette dernière référence, contrairement aux précédentes, est fréquentiste.

:::{.callout-tip}
### Histoire / Philosophie

McGrayne Sharon Bertsch, *The theory that would not die: how Bayes’ rule cracked the enigma code, hunted down Russian submarines, & emerged triumphant from two centuries of controversy*, New Haven, Yale university press, 2011.

Kennedy-Shaffer Lee, "Before p < 0.05 to Beyond p < 0.05: Using History to Contextualize p-Values and Significance Testing", *The American Statistician*, 2019, vol. 73, p. 82‑90.

Drouet Isabelle, *Le bayésianisme aujourd'hui: fondements et pratiques*, Paris, Éditions matériologiques, 2016.
:::

:::{.callout-tip}
### Principales librairies

- [Turing.jl](https://turinglang.org/) pour Julia.
- [PyMC](https://www.pymc.io/welcome.html) pour Python.
- [brms](http://paulbuerkner.com/brms/index.html) et [rstan](https://mc-stan.org/rstan/) pour R.
:::

# Réseaux bayésiens

:::{.callout-tip}
### Principales librairies

- [bnlearn](https://www.bnlearn.com/) en R.
- [pyagrum](https://pyagrum.readthedocs.io/en/stable/), [pgmpy](https://pgmpy.org), [BayesPy](https://bayespy.org/) & [pomegranate](https://pomegranate.readthedocs.io/en/stable/) (entre autres) en Python.
- [BayesNet](https://github.com/sisl/BayesNets.jl) pour Julia.
:::

# Maths

Nield Thomas, *Essential Math for Data Science*, O’Reilly, 2022, 349 p.

Savov Ivan, *No Bullshit Guide to Math and Physics*, Minireference Co, 2013, 288 p.
