---
title: "Styles"
date: 2024-10-21
---

Autour de vous s'amoncellent des témoignages, des lettres, des journaux intimes. Vous croulez sous une masse d'écrits du for privé. Deux solutions s'offrent à vous : picorer dans cette masse, citer ce qui vous plaît, délaisser ce qui vous dérange ; ou prendre tout, sans distinction, et vous laisser surprendre. Cette séance part d'une enquête sur l'expérience de la Première Guerre Mondiale, à travers les correspondances de paysans, d'ouvriers, d'instituteurs et d'écrivains. La question qu'on se posera est simple : la façon d'écrire la guerre reflète-t-elle la manière de la vivre ? Le style peut-il être une fenêtre sur l'expérience ? Dans la rubrique terre à terre : comment transformer un carton de lettres en base de données ? Comment assigner automatiquement une classe grammaticale à chaque mot d'un texte ? Comment caractériser, par des indicateurs simples, le style d'un scripteur ? Comment organiser les va-et-vient entre lecture immergée et lecture à distance ? Quelles représentations graphiques inventer pour stimuler l'interprétation ?